name: Cloudbeat-CI

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+"

jobs:
  Build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 0.53.1

      - name: Build
        id: build
        run: opa build -b ./bundle -e ./bundle/compliance

      - name: Check Branch Name
        run: |
          if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
            echo "The workflow was triggered on the 'main' branch."
          elif [[ ${{ github.ref }} =~ ^refs/heads/[0-9]+\.[0-9]+$ ]]; then
            echo "The workflow was triggered on a branch like '8.10' or similar."
          else
            echo "The workflow was triggered on a branch with an unknown name."
          fi
      - name: Publish
        if: steps.build.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(date +'%Y%m%d%H%M%S')
          title="v$tag" 
          is_latest=${{ github.base_ref == 'refs/heads/main' }}

          gh release create "$tag" \
             --repo=${{github.repository}} \
             --title="$title" \
             --generate-notes \
             --target ${{github.sha}} \
             --latest="$is_latest"
