name: Cloudbeat-CI

on:
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+"
    types: [opened, synchronize, reopened]

env:
  CONTAINER_SUFFIX: ${{ github.run_id }}
  CI_ELASTIC_AGENT_DOCKER_TAG: "8.7.0-SNAPSHOT"
  CI_ELASTIC_AGENT_DOCKER_IMAGE: "704479110758.dkr.ecr.eu-west-2.amazonaws.com/elastic-agent"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 0.53.1

      - name: build OPA bundle
        run: opa build -b ./bundle -e ./bundle/compliance

      - name: Create a release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.run_number }} \ 
            LICENSE.txt \
            --generate-notes \
            --target ${{github.base_ref}}
