name: Cloudbeat-CI

on:
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+"
    types: [opened, synchronize, reopened]

env:
  CONTAINER_SUFFIX: ${{ github.run_id }}
  CI_ELASTIC_AGENT_DOCKER_TAG: "8.7.0-SNAPSHOT"
  CI_ELASTIC_AGENT_DOCKER_IMAGE: "704479110758.dkr.ecr.eu-west-2.amazonaws.com/elastic-agent"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 0.53.1

      - name: build OPA bundle
        id: build
        run: opa build -b ./bundle -e ./bundle/compliance

      - name: Get Short Name of Base Ref
        id: get_base_ref_short_name
        run: echo "BASE_REF_SHORT_NAME=$(basename $GITHUB_BASE_REF)" >> $GITHUB_ENV

      - name: Create a release
        if: steps.build.outcome == 'success'
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Release.txt
          tag_name: "8.10"

    # env:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       tag: ${{ github.base_ref }}
    #     run: |
    #       gh release create "$tag" \
    #            --repo="$GITHUB_REPOSITORY" \
    #            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
    #            --generate-notes
    #            --target $tag
    #   gh release create v${{ github.run_number }} \
    #     LICENSE.txt \
    #     --generate-notes \
    #     --target ${{github.base_ref}}
