name: Update rules status

on:
  push:
    branches:
      - main

jobs:
  update_and_commit:
    name: Update and Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      # modifies README.md and RULES.md
      - name: Update rule status
        run: poetry run python dev/update_rule_status.py

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Rule Status
          committer: "Elastic Machine <elasticmachine@users.noreply.github.com>"
          author: "Elastic Machine <elasticmachine@users.noreply.github.com>"
          branch: update_rule_status
          delete-branch: true
          title: "Update rule status"
          body: |
            Update rule status

            - Updates README.md and RULES.md
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            documentation
          draft: false
